diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel_names: ["wheel1", "wheel3"]
  right_wheel_names: ["wheel2", "wheel4"]

  publish_rate: 50.0
  base_frame_id: base_link
  odom_frame_id: odom
  enable_odom_tf: true
  wheel_separation: 0.16  # Примерное значение, уточни по Webots модели
  wheel_radius: 0.05       # Примерное значение, уточни по модели
  pose_covariance_diagonal: [0.001, 0.001, 9999.0, 0.0, 0.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 9999.0, 0.0, 0.0, 0.03]