pointcloud_to_laserscan_node:
  ros__parameters:
    target_frame: "lidar_link"
    transform_tolerance: 0.01
    min_height: -1.0
    max_height: 1.0
    angle_increment: 0.005
    angle_min: -1.57  # -1.57 / 2
    angle_max: 1.57   # +1.57 / 2
    scan_time: 0.03
    range_min: 0.1
    range_max: 30.0
    use_inf: true
    inf_epsilon: 1.0
    voxel_filter: true
