corner1:
  position:
    x: 0.8505995980487503
    y: -0.84464454
  orientation:
    z: 0.0
    w: 1.0
corner2:
  position:
    x: 1.6462
    y: -0.9205654
  orientation:
    z: 0.0
    w: 1.0
corner3:
  position:
    x: 0.53813
    y: -2.1714
  orientation:
    z: 1.0
    w: 0.0
corner4:
  position:
    x: -0.1456
    y: -0.9454
  orientation:
    z: -0.7008
    w: 0.7098
corner5:
  position:
    x: 1.7383
    y: -1.5148
  orientation:
    z: -0.5804
    w: 0.8143
corner6:
  position:
    x: 2.8271
    y: -0.5734
  orientation:
    z: 0.6961
    w: 0.7179
corner7:
  position:
    x: 1.6849
    y: 0.3478
  orientation:
    z: 1.0
    w: 0.0
corner8:
  position:
    x: -0.1958
    y: -0.5319
  orientation:
    z: -0.9023
    w: -0.4309
